// Code generated by protoc-gen-go.
// source: protodata/flags.proto
// DO NOT EDIT!

/*
Package protodata is a generated protocol buffer package.

It is generated from these files:
	protodata/flags.proto
	protodata/login.proto

It has these top-level messages:
	FlagNum
	LoginRequest
	LoginResponse
*/
package protodata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FlagNum_Flag int32

const (
	FlagNum_eUnknown FlagNum_Flag = 0
	FlagNum_eNoUser  FlagNum_Flag = 1
)

var FlagNum_Flag_name = map[int32]string{
	0: "eUnknown",
	1: "eNoUser",
}
var FlagNum_Flag_value = map[string]int32{
	"eUnknown": 0,
	"eNoUser":  1,
}

func (x FlagNum_Flag) String() string {
	return proto.EnumName(FlagNum_Flag_name, int32(x))
}
func (FlagNum_Flag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type FlagNum struct {
}

func (m *FlagNum) Reset()                    { *m = FlagNum{} }
func (m *FlagNum) String() string            { return proto.CompactTextString(m) }
func (*FlagNum) ProtoMessage()               {}
func (*FlagNum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*FlagNum)(nil), "protodata.FlagNum")
	proto.RegisterEnum("protodata.FlagNum_Flag", FlagNum_Flag_name, FlagNum_Flag_value)
}

func init() { proto.RegisterFile("protodata/flags.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x4f, 0xcb, 0x49, 0x4c, 0x2f, 0xd6, 0x03, 0xf3, 0x85, 0x38,
	0xe1, 0xc2, 0x4a, 0x3a, 0x5c, 0xec, 0x6e, 0x39, 0x89, 0xe9, 0x7e, 0xa5, 0xb9, 0x4a, 0x8a, 0x5c,
	0x2c, 0x20, 0xa6, 0x10, 0x0f, 0x17, 0x47, 0x6a, 0x68, 0x5e, 0x76, 0x5e, 0x7e, 0x79, 0x9e, 0x00,
	0x83, 0x10, 0x37, 0x17, 0x7b, 0xaa, 0x5f, 0x7e, 0x68, 0x71, 0x6a, 0x91, 0x00, 0x63, 0x12, 0x1b,
	0x58, 0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x44, 0xfe, 0x57, 0x58, 0x00, 0x00, 0x00,
}
