// Code generated by protoc-gen-go.
// source: protodata/login.proto
// DO NOT EDIT!

package protodata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginRequest_MSGID int32

const (
	LoginRequest_unknown LoginRequest_MSGID = 0
	LoginRequest_ID      LoginRequest_MSGID = 1003
)

var LoginRequest_MSGID_name = map[int32]string{
	0:    "unknown",
	1003: "ID",
}
var LoginRequest_MSGID_value = map[string]int32{
	"unknown": 0,
	"ID":      1003,
}

func (x LoginRequest_MSGID) String() string {
	return proto.EnumName(LoginRequest_MSGID_name, int32(x))
}
func (LoginRequest_MSGID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0, 0} }

type LoginResponse_MSGID int32

const (
	LoginResponse_unknown LoginResponse_MSGID = 0
	LoginResponse_ID      LoginResponse_MSGID = 1004
)

var LoginResponse_MSGID_name = map[int32]string{
	0:    "unknown",
	1004: "ID",
}
var LoginResponse_MSGID_value = map[string]int32{
	"unknown": 0,
	"ID":      1004,
}

func (x LoginResponse_MSGID) String() string {
	return proto.EnumName(LoginResponse_MSGID_name, int32(x))
}
func (LoginResponse_MSGID) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1, 0} }

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Flag FlagNum_Flag `protobuf:"varint,1,opt,name=flag,enum=protodata.FlagNum_Flag" json:"flag,omitempty"`
	Desc string       `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LoginResponse) GetFlag() FlagNum_Flag {
	if m != nil {
		return m.Flag
	}
	return FlagNum_eUnknown
}

func (m *LoginResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "protodata.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protodata.LoginResponse")
	proto.RegisterEnum("protodata.LoginRequest_MSGID", LoginRequest_MSGID_name, LoginRequest_MSGID_value)
	proto.RegisterEnum("protodata.LoginResponse_MSGID", LoginResponse_MSGID_name, LoginResponse_MSGID_value)
}

func init() { proto.RegisterFile("protodata/login.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x03, 0xf3, 0x85, 0x38,
	0xe1, 0xc2, 0x52, 0x48, 0x2a, 0xd2, 0x72, 0x12, 0xd3, 0x8b, 0x21, 0x2a, 0x94, 0x52, 0xb9, 0x78,
	0x7c, 0x40, 0x1a, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x4a, 0x8b,
	0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x90,
	0x5c, 0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x44, 0x0e, 0xc6, 0x57, 0x92,
	0xe5, 0x62, 0xf5, 0x0d, 0x76, 0xf7, 0x74, 0x11, 0xe2, 0xe6, 0x62, 0x2f, 0xcd, 0xcb, 0xce, 0xcb,
	0x2f, 0xcf, 0x13, 0x60, 0x10, 0x62, 0xe7, 0x62, 0xf2, 0x74, 0x11, 0x78, 0xcd, 0xae, 0x94, 0xcf,
	0xc5, 0x0b, 0xb5, 0xa6, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x9b, 0x8b, 0x05, 0xe4, 0x0c,
	0xb0, 0x1d, 0x7c, 0x46, 0xe2, 0x7a, 0x70, 0xd7, 0xe9, 0xb9, 0xe5, 0x24, 0xa6, 0xfb, 0x95, 0xe6,
	0x82, 0xe9, 0x20, 0xb0, 0x22, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xd4, 0xe2, 0x64, 0xa8, 0xa5, 0x60,
	0x36, 0x5e, 0x0b, 0xdf, 0xb0, 0x27, 0xb1, 0x81, 0x0d, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xa3, 0xf7, 0xa0, 0xc3, 0x19, 0x01, 0x00, 0x00,
}
